name: Node.js CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: Project-7-CICD-NodeJS/package-lock.json

      - name: Install dependencies
        working-directory: Project-7-CICD-NodeJS
        run: npm ci

      - name: Run tests
        working-directory: Project-7-CICD-NodeJS
        run: npm test
  deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: test
    runs-on: [self-hosted, Linux, X64]

    steps:
      - name: Deploy application to EC2
        run: |
          set -e

          cd ~/aws-capstone-projects

          git fetch origin
          git reset --hard origin/main

          cd Project-7-CICD-NodeJS

          npm ci
          npm test

          pm2 restart project-7-cicd

          curl -f http://localhost:3000/health
